### ISSUE TITLE
reverted NXDOMAIN adblock

### ISSUE THREAD

**Issue by velzend** [tvwerkhoven/mikrotik_adblock#3]
Hi Tim,

Last evening I reverted the adblock functionality and removed all the static DNS entries.
I was first adblocking all DNS using the resolve to the local loopback interface (`127.0.0.1`), and next the `240.0.0.1` firewall reject method. Which were working very nice! 

Some of the issues we got after implementing the NXDOMAIN adblock:
 - Super slow loading of Netflix (frontpage) via Chromecast. Streaming videos is still super fast!
 - WhatsApp is not automatically receiving any new messages, no notifications...
 - Some webpages responding slower than rejecting.

I removed all the entries using:
- `/ip dns static`
- `delete list [ find ]`

And the Chromecast, and WhatsApp were working as expected again. 

I am still checking why adblocking DNS using NXDOMAIN is causing issues. 
Maybe application logic/ scripts are not yet taking this into account while rejecting is something developers widely know about?

**Comment by tvwerkhoven** [comment]
Thanks for the feedback. I don’t have these symptoms (yet). Just to check:

- you don’t have these problems with 127.0.0.1 style blocking?
- you use the same list of domains? 
- your router is performant enough? I notice my rb2011 is slow to add/remove dns entries when I have 6k static items.
- any specific websites this happens so I can test in my situation?
- does this happen on different devices? (Eg same webpage loads slow on multiple devices)

**Comment by velzend** [comment]
Hi Tim,

Thanks for the prompt reply. Nope I did not face the same problem with local loopback blocking nor the `240.0.0.1` method, the list of domains was older though (I did make a backup of the list so I can compare the differences). I will try to implement the new (NXDOMAIN) list of domains with refusing access using the resolve to `240.0.0.1` method, and see if I have the same behaviour. And/Or implement the old list using the NXDOMAIN technique.

WhatsApp only had issues on the iPhone of my wife, I did not face any issues.
I am using a Android phone (Oneplus 8+), and did not face any issues browsing the web etc. Netflix was still slow no matter what device started casting. Also on the laptop I did not face any issue. 

I am using the MikroTik hEX S and MikroTik cAP AC wireless access points. (so I assume I have enough resources available)

After three days I reverted the settings. And now the great Mikrotik Internet experience is restored (without any Ad blocking). 
Next thing when I have some spare time is to torch while doing Netflix and WhatsApp to see what network connectivity is going on. 

Keep you updated.  Any follow up ideas are welcome.

**Comment by velzend** [comment]
I think multiple Mikrotik access points had issues, which I resolved after restarting them... Meanwhile some updates were applied and I did not face the same issues for a while now... Also found your DNS blocking solution with NXDOMAIN to be very robust and super fast! I had zero issues, I did remove some entries from the blocking list for example the googlead endpoints.
